# Spring Datasource Configurations
spring.datasource.url=jdbc:postgresql://192.168.1.107:5432/iswcdb
spring.datasource.username=postgres
spring.datasource.password=nso1810
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Validate structure against existing tables (do not recreate/destroy)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8080
server.servlet.context-path=/api

# Logging level
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
